# Generated by Django 3.2.6 on 2021-08-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_row', models.IntegerField()),
                ('begin_col', models.IntegerField()),
                ('end_row', models.IntegerField()),
                ('end_col', models.IntegerField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='leaf_backend.receipt')),
            ],
            options={
                'unique_together': {('receipt', 'begin_row', 'begin_col', 'end_row', 'end_col')},
            },
        ),
    ]
